name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull knikhil007/cancer-prediction-app:latest
    - name: Delete Old Docker Container
      run: sudo docker rm -f cancer-pred-app
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cancer-pred-app knikhil007/cancer-prediction-app
