name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  
      - name: Lint code
        run: |
          pylint app

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t cancer-prediction-app .

      - name: Run container
        run: |
          docker run -p 8080:8080 cancer-prediction-app
          
      - name: Run tests
        run: |
          python app/test_app.py

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Build Docker Image
        run: |
          docker build -t knikhil007/cancer-prediction-app:latest .
          docker tag knikhil007/cancer-prediction-app:latest knikhil007/cancer-prediction-app:${{ github.sha }}
      - name: Push Docker Images
        run: |
          docker push knikhil007/cancer-prediction-app:latest
          docker push knikhil007/cancer-prediction-app:${{ github.sha }}
